version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - content-publishing-service

  frequency:
    image: frequencychain/instant-seal-node:latest
    ports:
      - 9944:9944
    networks:
      - content-publishing-service

  kubo_ipfs:
    image: ipfs/kubo:latest
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    networks:
      - content-publishing-service

  content-publishing-service-api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.docker.dev
    environment:
      - START_PROCESS=api
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/app
    depends_on:
      - redis
      - frequency
      - kubo_ipfs
    networks:
      - content-publishing-service

  content-publishing-service-worker:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env.docker.dev
    environment:
      - START_PROCESS=worker
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/app
    depends_on:
      - redis
      - frequency
      - kubo_ipfs
    networks:
      - content-publishing-service

volumes:
  redis_data:

networks:
  content-publishing-service:


