version: '3'

services:
  frequency:
    image: frequencychain/instant-seal-node:latest
    ports:
      - 9944:9944
  
  kubo_ipfs:
    image: ipfs/kubo:latest
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080

  content-publishing-service:
    depends_on:
      - frequency
      - kubo_ipfs
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000 # web server
      - 6379:6379 # redis inbuilt in docker
    env_file:
      - .env.docker.dev
    volumes:
    - ./:/app
volumes:
  redis_data:



